<a href="https://colab.research.google.com/github/Debayan97531/Pandas/blob/main/panda13joinappend.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#convinient method of combining columns of two potentially different index

#other,on,how,lsuffix,rsuffix

In [ ]:
import pandas as pd

In [ ]:
df1=pd.DataFrame({'A':[1,2,3],
                  'B':[50,60,70]},index=['a','b','c'])
df2=pd.DataFrame({'C':[4,5],
                  'D':[10,20]},index=['a','b'])
display(df1,df2)

   A   B
a  1  50
b  2  60
c  3  70

   C   D
a  4  10
b  5  20

In [ ]:
df1.join(df2)#value not filled for diff index

   A   B    C     D
a  1  50  4.0  10.0
b  2  60  5.0  20.0
c  3  70  NaN   NaN

In [ ]:
df1.join(df2)

   A   B    C     D
a  1  50  4.0  10.0
b  2  60  5.0  20.0
c  3  70  NaN   NaN

In [ ]:
df1.join(df2,how='right')#default left

   A   B  C   D
a  1  50  4  10
b  2  60  5  20

In [ ]:
df1.join(df2,how='outer')

   A   B    C     D
a  1  50  4.0  10.0
b  2  60  5.0  20.0
c  3  70  NaN   NaN

In [ ]:
#to add dataframes of same column use lsuffix/rsuffix
df1=pd.DataFrame({'A':[1,2,3],
                  'B':[50,60,70]},index=['a','b','c'])
df2=pd.DataFrame({'A':[4,5],
                  'D':[10,20]},index=['a','b'])
display(df1,df2)

   A   B
a  1  50
b  2  60
c  3  70

   A   D
a  4  10
b  5  20

In [ ]:
df1.join(df2,lsuffix='_1')

   A_1   B    A     D
a    1  50  4.0  10.0
b    2  60  5.0  20.0
c    3  70  NaN   NaN

In [ ]:
df1.join(df2,rsuffix='_1')

   A   B  A_1     D
a  1  50  4.0  10.0
b  2  60  5.0  20.0
c  3  70  NaN   NaN

##append function used to append rows of other dataframe to end of given dataframe,returning a new dataframe object

#other,lgnore_index,sort

In [ ]:
df3=pd.DataFrame({'A':[1,2,3],
                  'B':[50,70,89]})
df4=pd.DataFrame({'C':[4,5,6],
                  'B':[40,30,28]})
display(df3,df4)

   A   B
0  1  50
1  2  70
2  3  89

   C   B
0  4  40
1  5  30
2  6  28

In [ ]:
df3.append(df4)

     A   B    C
0  1.0  50  NaN
1  2.0  70  NaN
2  3.0  89  NaN
0  NaN  40  4.0
1  NaN  30  5.0
2  NaN  28  6.0

In [ ]:
df3.append(df4,ignore_index=True)

     A   B    C
0  1.0  50  NaN
1  2.0  70  NaN
2  3.0  89  NaN
3  NaN  40  4.0
4  NaN  30  5.0
5  NaN  28  6.0

In [ ]:
df4.append(df3,ignore_index=True)

     C   B    A
0  4.0  40  NaN
1  5.0  30  NaN
2  6.0  28  NaN
3  NaN  50  1.0
4  NaN  70  2.0
5  NaN  89  3.0